// Bundle the Studio guest MCP-App into a single self-contained IIFE and emit it
// as a TS string constant that ui.ts inlines into the ui:// resource HTML.
import { build } from 'esbuild'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

const result = await build({
  entryPoints: [resolve(root, 'guest/studio-app.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  write: false,
  legalComments: 'none'
})

const code = result.outputFiles[0].text
const out = resolve(root, 'src/guestBundle.generated.ts')
writeFileSync(
  out,
  '// AUTO-GENERATED by scripts/build-guest.mjs — do not edit.\n' +
    `export const GUEST_BUNDLE: string = ${JSON.stringify(code)}\n`
)
console.log(`guest bundle: ${(code.length / 1024).toFixed(1)} KiB -> src/guestBundle.generated.ts`)
